name: macro_calculator
description: A new Flutter project.
version: 3.3.0+7

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  eva_icons_flutter: ^3.0.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  numberpicker: ^2.1.1
  path_provider: ^2.0.2
  provider: ^5.0.0
  screenshot: ^1.2.1
  share_plus: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
